### ISSUE TITLE
InterCon Preparations

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/interspace.chat#16]
Just going to lump all of these together.
We need links to things on the outside:
- Telegram
- Timetable
- Hub for each room
- Youtube streams
- Gitcoin community call
- Maybe an extra empty room?

And need a [pretopia](https://twitter.com/PretopiaFM) watermark down there in bottom left corner, as they are sponsoring the event.

It would be great if there was a pop-up as soon as people join,
a popup that tells them:
1. Try to join the jitsi room, but maybe it's up to capacity and you get kicked
2. So try joining the Hub watching session, but maybe it's full
3. So go watch livestream on youtube.

**Comment by c0mput3rxz** [comment]
Telegram link for InfoCon: https://t.me/intercon13
