### ISSUE TITLE
Remove a bunch of things

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/interspace.chat#30]
Didn't want to create a separate issue for each one as they seem small; here's what I'd like removed from Interspace and why:

- Remove "Sponsored by Pretopia", this was for InterCon only
- Remove the opening [warning window](http://prntscr.com/rhb9wv), again because it was only for InterCon

Things that add to the clutter and should probably be removed:
- Remove "click to join rooms", as it's fairly obvious since the houses are the only thing you can click anyway
- Remove the "position your window" text that pops once you "open a house", as it's obvious to anyone who ever used any desktop OS.

**Comment by manolingam** [comment]
Done. Created a pull request.
