### ISSUE TITLE
Make room names show on mouse hover only

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/interspace.chat#31]
It already detracts from the aesthetics, and as we add more and more buildings it will make zero sense to keep it as is.
It would probably make sense for the names of the houses to show only on mouse hover.
Makes it prettier and adds some fun for the newcomers to discover things on their own vs just being told what is what as soon as they open.
At some point this will be less overwhelming than actually showing everything right away.

Side quest: Add a "?" button somewhere outside the octopus, clicking it toggles name displaying on/off

**Comment by nicolas-law** [comment]
Pull request #37 implements the hover functionality to show room names, which are now hidden by default.
However, it doesn't implement the side quest ;)
