### ISSUE TITLE
Add Discord to Interspace (copy from another repo)

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/interspace.chat#35]
It would be good for Interspace to have Discord for obvious reasons... 
The Interspace.chat team already implemented it, so it's a matter of going to [their repo](https://github.com/interspacechat) & copying some code?

**Comment by geleeroyale** [comment]
There is an older version of the same issue. Yea -  I have it working on https://staging.interspace.chat and can merge back. We use titanembeds which is after all my research the best way to embed discord chats into a website.

**Comment by peth-yursick** [comment]
perfect, thank you for noting!
